// Word pairs for Word Spy.
// civilian = the word most players get. spy = the similar word the impostor gets.

module.exports = [
  { category: 'Drinks',      civilian: 'Coffee',      spy: 'Tea' },
  { category: 'Drinks',      civilian: 'Beer',        spy: 'Wine' },
  { category: 'Drinks',      civilian: 'Milk',        spy: 'Juice' },
  { category: 'Drinks',      civilian: 'Lemonade',    spy: 'Soda' },

  { category: 'Animals',     civilian: 'Cat',         spy: 'Dog' },
  { category: 'Animals',     civilian: 'Lion',        spy: 'Tiger' },
  { category: 'Animals',     civilian: 'Butterfly',   spy: 'Bee' },
  { category: 'Animals',     civilian: 'Shark',       spy: 'Dolphin' },
  { category: 'Animals',     civilian: 'Eagle',       spy: 'Hawk' },
  { category: 'Animals',     civilian: 'Rabbit',      spy: 'Squirrel' },
  { category: 'Animals',     civilian: 'Horse',       spy: 'Donkey' },
  { category: 'Animals',     civilian: 'Crocodile',   spy: 'Alligator' },

  { category: 'Food',        civilian: 'Pizza',       spy: 'Burger' },
  { category: 'Food',        civilian: 'Sushi',       spy: 'Dumpling' },
  { category: 'Food',        civilian: 'Sandwich',    spy: 'Taco' },
  { category: 'Food',        civilian: 'Pancake',     spy: 'Waffle' },
  { category: 'Food',        civilian: 'Pasta',       spy: 'Noodles' },
  { category: 'Food',        civilian: 'Cake',        spy: 'Pie' },
  { category: 'Food',        civilian: 'Ice Cream',   spy: 'Yogurt' },
  { category: 'Food',        civilian: 'Doughnut',    spy: 'Bagel' },
  { category: 'Food',        civilian: 'Bread',       spy: 'Rice' },
  { category: 'Food',        civilian: 'Chocolate',   spy: 'Candy' },
  { category: 'Food',        civilian: 'Honey',       spy: 'Syrup' },

  { category: 'Fruit',       civilian: 'Apple',       spy: 'Orange' },
  { category: 'Fruit',       civilian: 'Banana',      spy: 'Mango' },
  { category: 'Fruit',       civilian: 'Strawberry',  spy: 'Raspberry' },
  { category: 'Fruit',       civilian: 'Watermelon',  spy: 'Cantaloupe' },

  { category: 'Sports',      civilian: 'Soccer',      spy: 'Basketball' },
  { category: 'Sports',      civilian: 'Baseball',    spy: 'Cricket' },
  { category: 'Sports',      civilian: 'Tennis',      spy: 'Badminton' },
  { category: 'Sports',      civilian: 'Golf',        spy: 'Billiards' },
  { category: 'Sports',      civilian: 'Hockey',      spy: 'Lacrosse' },
  { category: 'Sports',      civilian: 'Boxing',      spy: 'Wrestling' },
  { category: 'Sports',      civilian: 'Swimming',    spy: 'Diving' },
  { category: 'Sports',      civilian: 'Skiing',      spy: 'Snowboarding' },

  { category: 'Places',      civilian: 'Beach',       spy: 'Desert' },
  { category: 'Places',      civilian: 'Mountain',    spy: 'Hill' },
  { category: 'Places',      civilian: 'Forest',      spy: 'Jungle' },
  { category: 'Places',      civilian: 'River',       spy: 'Lake' },
  { category: 'Places',      civilian: 'City',        spy: 'Town' },
  { category: 'Places',      civilian: 'School',      spy: 'University' },
  { category: 'Places',      civilian: 'Library',     spy: 'Bookstore' },
  { category: 'Places',      civilian: 'Hospital',    spy: 'Clinic' },
  { category: 'Places',      civilian: 'Castle',      spy: 'Fortress' },
  { category: 'Places',      civilian: 'Airport',     spy: 'Train Station' },

  { category: 'Transport',   civilian: 'Car',         spy: 'Truck' },
  { category: 'Transport',   civilian: 'Bicycle',     spy: 'Motorcycle' },
  { category: 'Transport',   civilian: 'Train',       spy: 'Bus' },
  { category: 'Transport',   civilian: 'Plane',       spy: 'Helicopter' },
  { category: 'Transport',   civilian: 'Boat',        spy: 'Ship' },
  { category: 'Transport',   civilian: 'Skateboard',  spy: 'Scooter' },

  { category: 'Weather',     civilian: 'Rain',        spy: 'Snow' },
  { category: 'Weather',     civilian: 'Thunder',     spy: 'Lightning' },
  { category: 'Weather',     civilian: 'Fog',         spy: 'Mist' },
  { category: 'Weather',     civilian: 'Tornado',     spy: 'Hurricane' },

  { category: 'Nature',      civilian: 'Sun',         spy: 'Moon' },
  { category: 'Nature',      civilian: 'Fire',        spy: 'Lava' },
  { category: 'Nature',      civilian: 'Ocean',       spy: 'Pool' },
  { category: 'Nature',      civilian: 'Rose',        spy: 'Tulip' },
  { category: 'Nature',      civilian: 'Tree',        spy: 'Bush' },

  { category: 'Music',       civilian: 'Piano',       spy: 'Guitar' },
  { category: 'Music',       civilian: 'Violin',      spy: 'Cello' },
  { category: 'Music',       civilian: 'Drum',        spy: 'Tambourine' },
  { category: 'Music',       civilian: 'Flute',       spy: 'Clarinet' },

  { category: 'Jobs',        civilian: 'Doctor',      spy: 'Nurse' },
  { category: 'Jobs',        civilian: 'Teacher',     spy: 'Professor' },
  { category: 'Jobs',        civilian: 'Chef',        spy: 'Baker' },
  { category: 'Jobs',        civilian: 'Firefighter', spy: 'Police Officer' },
  { category: 'Jobs',        civilian: 'Actor',       spy: 'Singer' },
  { category: 'Jobs',        civilian: 'Pilot',       spy: 'Astronaut' },

  { category: 'Fantasy',     civilian: 'Pirate',      spy: 'Viking' },
  { category: 'Fantasy',     civilian: 'Ghost',       spy: 'Zombie' },
  { category: 'Fantasy',     civilian: 'Witch',       spy: 'Wizard' },
  { category: 'Fantasy',     civilian: 'Dragon',      spy: 'Dinosaur' },
  { category: 'Fantasy',     civilian: 'Robot',       spy: 'Cyborg' },
  { category: 'Fantasy',     civilian: 'Vampire',     spy: 'Werewolf' },
  { category: 'Fantasy',     civilian: 'Fairy',       spy: 'Angel' },

  { category: 'Objects',     civilian: 'Pen',         spy: 'Pencil' },
  { category: 'Objects',     civilian: 'Book',        spy: 'Magazine' },
  { category: 'Objects',     civilian: 'Laptop',      spy: 'Tablet' },
  { category: 'Objects',     civilian: 'Camera',      spy: 'Phone' },
  { category: 'Objects',     civilian: 'Watch',       spy: 'Clock' },
  { category: 'Objects',     civilian: 'Backpack',    spy: 'Suitcase' },
  { category: 'Objects',     civilian: 'Umbrella',    spy: 'Raincoat' },
  { category: 'Objects',     civilian: 'Fork',        spy: 'Spoon' },
  { category: 'Objects',     civilian: 'Knife',       spy: 'Scissors' },
  { category: 'Objects',     civilian: 'Glasses',     spy: 'Sunglasses' },

  { category: 'Clothing',    civilian: 'Hat',         spy: 'Cap' },
  { category: 'Clothing',    civilian: 'Shoes',       spy: 'Boots' },
  { category: 'Clothing',    civilian: 'Ring',        spy: 'Necklace' },
  { category: 'Clothing',    civilian: 'Jacket',      spy: 'Sweater' },
  { category: 'Clothing',    civilian: 'Jeans',       spy: 'Shorts' },

  { category: 'Furniture',   civilian: 'Sofa',        spy: 'Chair' },
  { category: 'Furniture',   civilian: 'Bed',         spy: 'Hammock' },
  { category: 'Furniture',   civilian: 'Table',       spy: 'Desk' },
  { category: 'Furniture',   civilian: 'Lamp',        spy: 'Candle' },

  { category: 'Toys / Games', civilian: 'Chess',      spy: 'Checkers' },
  { category: 'Toys / Games', civilian: 'Lego',       spy: 'Puzzle' },
  { category: 'Toys / Games', civilian: 'Kite',       spy: 'Balloon' },
  { category: 'Toys / Games', civilian: 'Dominoes',   spy: 'Dice' },
  { category: 'Toys / Games', civilian: 'Yo-yo',      spy: 'Spinner' },
  { category: 'Toys / Games', civilian: 'Frisbee',    spy: 'Boomerang' },

  // ---- additions ----

  { category: 'Drinks',      civilian: 'Smoothie',    spy: 'Milkshake' },
  { category: 'Drinks',      civilian: 'Latte',       spy: 'Cappuccino' },
  { category: 'Drinks',      civilian: 'Cola',        spy: 'Root Beer' },

  { category: 'Animals',     civilian: 'Elephant',    spy: 'Rhino' },
  { category: 'Animals',     civilian: 'Giraffe',     spy: 'Camel' },
  { category: 'Animals',     civilian: 'Penguin',     spy: 'Puffin' },
  { category: 'Animals',     civilian: 'Owl',         spy: 'Bat' },
  { category: 'Animals',     civilian: 'Kangaroo',    spy: 'Koala' },
  { category: 'Animals',     civilian: 'Wolf',        spy: 'Fox' },
  { category: 'Animals',     civilian: 'Bear',        spy: 'Gorilla' },
  { category: 'Animals',     civilian: 'Turtle',      spy: 'Tortoise' },
  { category: 'Animals',     civilian: 'Snake',       spy: 'Lizard' },
  { category: 'Animals',     civilian: 'Monkey',      spy: 'Ape' },
  { category: 'Animals',     civilian: 'Duck',        spy: 'Goose' },
  { category: 'Animals',     civilian: 'Deer',        spy: 'Moose' },
  { category: 'Animals',     civilian: 'Whale',       spy: 'Seal' },
  { category: 'Animals',     civilian: 'Octopus',     spy: 'Squid' },
  { category: 'Animals',     civilian: 'Crab',        spy: 'Lobster' },
  { category: 'Animals',     civilian: 'Frog',        spy: 'Toad' },
  { category: 'Animals',     civilian: 'Hamster',     spy: 'Guinea Pig' },
  { category: 'Animals',     civilian: 'Peacock',     spy: 'Flamingo' },

  { category: 'Food',        civilian: 'Ramen',       spy: 'Pho' },
  { category: 'Food',        civilian: 'Omelette',    spy: 'Frittata' },
  { category: 'Food',        civilian: 'Kebab',       spy: 'Gyro' },
  { category: 'Food',        civilian: 'Pretzel',     spy: 'Churro' },
  { category: 'Food',        civilian: 'Hot Dog',     spy: 'Bratwurst' },
  { category: 'Food',        civilian: 'Lasagna',     spy: 'Spaghetti' },
  { category: 'Food',        civilian: 'Quesadilla',  spy: 'Burrito' },
  { category: 'Food',        civilian: 'Curry',       spy: 'Stew' },
  { category: 'Food',        civilian: 'Bacon',       spy: 'Ham' },
  { category: 'Food',        civilian: 'Soup',        spy: 'Broth' },

  { category: 'Fruit',       civilian: 'Grape',       spy: 'Cherry' },
  { category: 'Fruit',       civilian: 'Pineapple',   spy: 'Coconut' },
  { category: 'Fruit',       civilian: 'Lemon',       spy: 'Lime' },
  { category: 'Fruit',       civilian: 'Peach',       spy: 'Nectarine' },
  { category: 'Fruit',       civilian: 'Blueberry',   spy: 'Blackberry' },
  { category: 'Fruit',       civilian: 'Plum',        spy: 'Apricot' },

  { category: 'Sports',      civilian: 'Rugby',       spy: 'American Football' },
  { category: 'Sports',      civilian: 'Volleyball',  spy: 'Handball' },
  { category: 'Sports',      civilian: 'Karate',      spy: 'Judo' },
  { category: 'Sports',      civilian: 'Archery',     spy: 'Darts' },
  { category: 'Sports',      civilian: 'Surfing',     spy: 'Windsurfing' },
  { category: 'Sports',      civilian: 'Rowing',      spy: 'Kayaking' },

  { category: 'Places',      civilian: 'Park',        spy: 'Garden' },
  { category: 'Places',      civilian: 'Zoo',         spy: 'Aquarium' },
  { category: 'Places',      civilian: 'Museum',      spy: 'Gallery' },
  { category: 'Places',      civilian: 'Cafe',        spy: 'Diner' },
  { category: 'Places',      civilian: 'Farm',        spy: 'Ranch' },
  { category: 'Places',      civilian: 'Tower',       spy: 'Skyscraper' },
  { category: 'Places',      civilian: 'Palace',      spy: 'Mansion' },
  { category: 'Places',      civilian: 'Cave',        spy: 'Tunnel' },
  { category: 'Places',      civilian: 'Stadium',     spy: 'Arena' },
  { category: 'Places',      civilian: 'Theater',     spy: 'Cinema' },
  { category: 'Places',      civilian: 'Temple',      spy: 'Church' },

  { category: 'Transport',   civilian: 'Subway',      spy: 'Tram' },
  { category: 'Transport',   civilian: 'Ferry',       spy: 'Cruise Ship' },
  { category: 'Transport',   civilian: 'Submarine',   spy: 'Yacht' },
  { category: 'Transport',   civilian: 'Tractor',     spy: 'Bulldozer' },
  { category: 'Transport',   civilian: 'Van',         spy: 'Minivan' },
  { category: 'Transport',   civilian: 'Ambulance',   spy: 'Fire Truck' },
  { category: 'Transport',   civilian: 'Hot Air Balloon', spy: 'Blimp' },

  { category: 'Weather',     civilian: 'Hailstorm',   spy: 'Blizzard' },
  { category: 'Weather',     civilian: 'Drizzle',     spy: 'Shower' },
  { category: 'Weather',     civilian: 'Heatwave',    spy: 'Drought' },

  { category: 'Nature',      civilian: 'Cactus',      spy: 'Succulent' },
  { category: 'Nature',      civilian: 'Oak',         spy: 'Pine' },
  { category: 'Nature',      civilian: 'Waterfall',   spy: 'Fountain' },
  { category: 'Nature',      civilian: 'Volcano',     spy: 'Geyser' },
  { category: 'Nature',      civilian: 'Glacier',     spy: 'Iceberg' },
  { category: 'Nature',      civilian: 'Rainbow',     spy: 'Aurora' },
  { category: 'Nature',      civilian: 'Valley',      spy: 'Canyon' },
  { category: 'Nature',      civilian: 'Island',      spy: 'Peninsula' },

  { category: 'Music',       civilian: 'Trumpet',     spy: 'Trombone' },
  { category: 'Music',       civilian: 'Saxophone',   spy: 'Oboe' },
  { category: 'Music',       civilian: 'Harp',        spy: 'Xylophone' },
  { category: 'Music',       civilian: 'Accordion',   spy: 'Harmonica' },

  { category: 'Jobs',        civilian: 'Scientist',   spy: 'Engineer' },
  { category: 'Jobs',        civilian: 'Lawyer',      spy: 'Judge' },
  { category: 'Jobs',        civilian: 'Writer',      spy: 'Journalist' },
  { category: 'Jobs',        civilian: 'Carpenter',   spy: 'Plumber' },
  { category: 'Jobs',        civilian: 'Mechanic',    spy: 'Electrician' },
  { category: 'Jobs',        civilian: 'Dentist',     spy: 'Optometrist' },
  { category: 'Jobs',        civilian: 'Barber',      spy: 'Hairdresser' },
  { category: 'Jobs',        civilian: 'Magician',    spy: 'Juggler' },
  { category: 'Jobs',        civilian: 'Photographer', spy: 'Videographer' },

  { category: 'Fantasy',     civilian: 'Knight',      spy: 'Samurai' },
  { category: 'Fantasy',     civilian: 'Mermaid',     spy: 'Siren' },
  { category: 'Fantasy',     civilian: 'Unicorn',     spy: 'Pegasus' },
  { category: 'Fantasy',     civilian: 'Goblin',      spy: 'Troll' },
  { category: 'Fantasy',     civilian: 'Elf',         spy: 'Dwarf' },
  { category: 'Fantasy',     civilian: 'Alien',       spy: 'UFO' },
  { category: 'Fantasy',     civilian: 'Ninja',       spy: 'Assassin' },
  { category: 'Fantasy',     civilian: 'Phoenix',     spy: 'Griffin' },

  { category: 'Objects',     civilian: 'Keyboard',    spy: 'Mouse' },
  { category: 'Objects',     civilian: 'Headphones',  spy: 'Earbuds' },
  { category: 'Objects',     civilian: 'Mirror',      spy: 'Window' },
  { category: 'Objects',     civilian: 'Flashlight',  spy: 'Lantern' },
  { category: 'Objects',     civilian: 'Key',         spy: 'Lock' },
  { category: 'Objects',     civilian: 'Map',         spy: 'Compass' },
  { category: 'Objects',     civilian: 'Wallet',      spy: 'Purse' },
  { category: 'Objects',     civilian: 'Brush',       spy: 'Comb' },
  { category: 'Objects',     civilian: 'Soap',        spy: 'Shampoo' },
  { category: 'Objects',     civilian: 'Pillow',      spy: 'Blanket' },
  { category: 'Objects',     civilian: 'Plate',       spy: 'Bowl' },
  { category: 'Objects',     civilian: 'Cup',         spy: 'Mug' },
  { category: 'Objects',     civilian: 'Bottle',      spy: 'Can' },

  { category: 'Clothing',    civilian: 'T-shirt',     spy: 'Tank Top' },
  { category: 'Clothing',    civilian: 'Dress',       spy: 'Skirt' },
  { category: 'Clothing',    civilian: 'Socks',       spy: 'Tights' },
  { category: 'Clothing',    civilian: 'Tie',         spy: 'Bowtie' },
  { category: 'Clothing',    civilian: 'Scarf',       spy: 'Shawl' },
  { category: 'Clothing',    civilian: 'Gloves',      spy: 'Mittens' },
  { category: 'Clothing',    civilian: 'Belt',        spy: 'Suspenders' },
  { category: 'Clothing',    civilian: 'Suit',        spy: 'Tuxedo' },
  { category: 'Clothing',    civilian: 'Hoodie',      spy: 'Sweatshirt' },

  { category: 'Furniture',   civilian: 'Bookshelf',   spy: 'Cabinet' },
  { category: 'Furniture',   civilian: 'Dresser',     spy: 'Wardrobe' },
  { category: 'Furniture',   civilian: 'Rug',         spy: 'Carpet' },
  { category: 'Furniture',   civilian: 'Stool',       spy: 'Bench' },
  { category: 'Furniture',   civilian: 'Fireplace',   spy: 'Stove' },

  // ---- new categories ----

  { category: 'Insects',     civilian: 'Ant',         spy: 'Termite' },
  { category: 'Insects',     civilian: 'Spider',      spy: 'Scorpion' },
  { category: 'Insects',     civilian: 'Ladybug',     spy: 'Beetle' },
  { category: 'Insects',     civilian: 'Wasp',        spy: 'Hornet' },
  { category: 'Insects',     civilian: 'Fly',         spy: 'Mosquito' },
  { category: 'Insects',     civilian: 'Dragonfly',   spy: 'Firefly' },
  { category: 'Insects',     civilian: 'Cricket',     spy: 'Grasshopper' },

  { category: 'Desserts',    civilian: 'Brownie',     spy: 'Cookie' },
  { category: 'Desserts',    civilian: 'Cupcake',     spy: 'Muffin' },
  { category: 'Desserts',    civilian: 'Tiramisu',    spy: 'Cheesecake' },
  { category: 'Desserts',    civilian: 'Sorbet',      spy: 'Gelato' },
  { category: 'Desserts',    civilian: 'Eclair',      spy: 'Cannoli' },
  { category: 'Desserts',    civilian: 'Pudding',     spy: 'Custard' },
  { category: 'Desserts',    civilian: 'Macaron',     spy: 'Meringue' },

  { category: 'Space',       civilian: 'Earth',       spy: 'Mars' },
  { category: 'Space',       civilian: 'Saturn',      spy: 'Jupiter' },
  { category: 'Space',       civilian: 'Asteroid',    spy: 'Meteor' },
  { category: 'Space',       civilian: 'Galaxy',      spy: 'Nebula' },
  { category: 'Space',       civilian: 'Rocket',      spy: 'Shuttle' },
  { category: 'Space',       civilian: 'Telescope',   spy: 'Binoculars' },

  { category: 'Vegetables',  civilian: 'Carrot',      spy: 'Potato' },
  { category: 'Vegetables',  civilian: 'Broccoli',    spy: 'Cauliflower' },
  { category: 'Vegetables',  civilian: 'Lettuce',     spy: 'Cabbage' },
  { category: 'Vegetables',  civilian: 'Onion',       spy: 'Garlic' },
  { category: 'Vegetables',  civilian: 'Tomato',      spy: 'Pepper' },
  { category: 'Vegetables',  civilian: 'Cucumber',    spy: 'Zucchini' },
  { category: 'Vegetables',  civilian: 'Pumpkin',     spy: 'Squash' },
  { category: 'Vegetables',  civilian: 'Corn',        spy: 'Peas' },
  { category: 'Vegetables',  civilian: 'Spinach',     spy: 'Kale' },

  { category: 'Tools',       civilian: 'Hammer',      spy: 'Wrench' },
  { category: 'Tools',       civilian: 'Saw',         spy: 'Drill' },
  { category: 'Tools',       civilian: 'Screwdriver', spy: 'Pliers' },
  { category: 'Tools',       civilian: 'Shovel',      spy: 'Rake' },
  { category: 'Tools',       civilian: 'Ladder',      spy: 'Stepstool' },
  { category: 'Tools',       civilian: 'Axe',         spy: 'Machete' },

  { category: 'Body',        civilian: 'Ear',         spy: 'Eye' },
  { category: 'Body',        civilian: 'Nose',        spy: 'Mouth' },
  { category: 'Body',        civilian: 'Hand',        spy: 'Foot' },
  { category: 'Body',        civilian: 'Elbow',       spy: 'Knee' },
  { category: 'Body',        civilian: 'Finger',      spy: 'Toe' },
  { category: 'Body',        civilian: 'Heart',       spy: 'Brain' },

  // ---- round 3 additions ----

  { category: 'Drinks',      civilian: 'Espresso',    spy: 'Americano' },
  { category: 'Drinks',      civilian: 'Iced Tea',    spy: 'Lemonade' },
  { category: 'Drinks',      civilian: 'Eggnog',      spy: 'Hot Cocoa' },
  { category: 'Drinks',      civilian: 'Matcha',      spy: 'Green Tea' },
  { category: 'Drinks',      civilian: 'Mojito',      spy: 'Margarita' },
  { category: 'Drinks',      civilian: 'Ginger Ale',  spy: 'Tonic Water' },

  { category: 'Animals',     civilian: 'Parrot',      spy: 'Toucan' },
  { category: 'Animals',     civilian: 'Pelican',     spy: 'Stork' },
  { category: 'Animals',     civilian: 'Cheetah',     spy: 'Leopard' },
  { category: 'Animals',     civilian: 'Hedgehog',    spy: 'Porcupine' },
  { category: 'Animals',     civilian: 'Ferret',      spy: 'Weasel' },
  { category: 'Animals',     civilian: 'Pigeon',      spy: 'Dove' },
  { category: 'Animals',     civilian: 'Salmon',      spy: 'Trout' },
  { category: 'Animals',     civilian: 'Llama',       spy: 'Alpaca' },

  { category: 'Food',        civilian: 'Popcorn',     spy: 'Nachos' },
  { category: 'Food',        civilian: 'Meatball',    spy: 'Dumpling' },
  { category: 'Food',        civilian: 'Croissant',   spy: 'Baguette' },
  { category: 'Food',        civilian: 'Ceviche',     spy: 'Sashimi' },
  { category: 'Food',        civilian: 'Empanada',    spy: 'Samosa' },
  { category: 'Food',        civilian: 'Grilled Cheese', spy: 'Panini' },
  { category: 'Food',        civilian: 'Smoothie Bowl', spy: 'Acai Bowl' },
  { category: 'Food',        civilian: 'Poutine',     spy: 'Loaded Fries' },

  { category: 'Fruit',       civilian: 'Fig',         spy: 'Date' },
  { category: 'Fruit',       civilian: 'Papaya',      spy: 'Guava' },
  { category: 'Fruit',       civilian: 'Pomegranate', spy: 'Passionfruit' },
  { category: 'Fruit',       civilian: 'Grapefruit',  spy: 'Tangerine' },
  { category: 'Fruit',       civilian: 'Cranberry',   spy: 'Currant' },

  { category: 'Sports',      civilian: 'Squash',      spy: 'Racquetball' },
  { category: 'Sports',      civilian: 'Gymnastics',  spy: 'Figure Skating' },
  { category: 'Sports',      civilian: 'Polo',        spy: 'Croquet' },
  { category: 'Sports',      civilian: 'Triathlon',   spy: 'Decathlon' },
  { category: 'Sports',      civilian: 'Softball',    spy: 'Rounders' },
  { category: 'Sports',      civilian: 'Paragliding', spy: 'Hang Gliding' },

  { category: 'Places',      civilian: 'Lighthouse',  spy: 'Watchtower' },
  { category: 'Places',      civilian: 'Cabin',       spy: 'Treehouse' },
  { category: 'Places',      civilian: 'Rooftop',     spy: 'Balcony' },
  { category: 'Places',      civilian: 'Market',      spy: 'Bazaar' },
  { category: 'Places',      civilian: 'Pier',        spy: 'Boardwalk' },
  { category: 'Places',      civilian: 'Igloo',       spy: 'Tent' },
  { category: 'Places',      civilian: 'Laundromat',  spy: 'Dry Cleaner' },
  { category: 'Places',      civilian: 'Pharmacy',    spy: 'Dispensary' },

  { category: 'Transport',   civilian: 'Canoe',       spy: 'Kayak' },
  { category: 'Transport',   civilian: 'Segway',      spy: 'Hoverboard' },
  { category: 'Transport',   civilian: 'Rickshaw',    spy: 'Carriage' },
  { category: 'Transport',   civilian: 'Gondola',     spy: 'Cable Car' },
  { category: 'Transport',   civilian: 'Go-kart',     spy: 'Bumper Car' },
  { category: 'Transport',   civilian: 'Jet',         spy: 'Prop Plane' },

  { category: 'Weather',     civilian: 'Sleet',       spy: 'Frost' },
  { category: 'Weather',     civilian: 'Cyclone',     spy: 'Typhoon' },
  { category: 'Weather',     civilian: 'Breeze',      spy: 'Gust' },
  { category: 'Weather',     civilian: 'Smog',        spy: 'Haze' },

  { category: 'Nature',      civilian: 'Coral',       spy: 'Anemone' },
  { category: 'Nature',      civilian: 'Dune',        spy: 'Cliff' },
  { category: 'Nature',      civilian: 'Swamp',       spy: 'Marsh' },
  { category: 'Nature',      civilian: 'Moss',        spy: 'Lichen' },
  { category: 'Nature',      civilian: 'Pebble',      spy: 'Boulder' },
  { category: 'Nature',      civilian: 'Tide',        spy: 'Wave' },
  { category: 'Nature',      civilian: 'Stalactite',  spy: 'Stalagmite' },

  { category: 'Music',       civilian: 'Banjo',       spy: 'Mandolin' },
  { category: 'Music',       civilian: 'Organ',       spy: 'Synthesizer' },
  { category: 'Music',       civilian: 'Ukulele',     spy: 'Lute' },
  { category: 'Music',       civilian: 'Bongo',       spy: 'Conga' },
  { category: 'Music',       civilian: 'Didgeridoo',  spy: 'Bagpipe' },

  { category: 'Jobs',        civilian: 'Architect',   spy: 'Interior Designer' },
  { category: 'Jobs',        civilian: 'Surgeon',     spy: 'Paramedic' },
  { category: 'Jobs',        civilian: 'Archaeologist', spy: 'Paleontologist' },
  { category: 'Jobs',        civilian: 'Waiter',      spy: 'Bartender' },
  { category: 'Jobs',        civilian: 'Lifeguard',   spy: 'Park Ranger' },

  { category: 'Fantasy',     civilian: 'Witch Doctor', spy: 'Shaman' },
  { category: 'Fantasy',     civilian: 'Werewolf',    spy: 'Shapeshifter' },
  { category: 'Fantasy',     civilian: 'Kraken',      spy: 'Leviathan' },
  { category: 'Fantasy',     civilian: 'Centaur',     spy: 'Minotaur' },
  { category: 'Fantasy',     civilian: 'Leprechaun',  spy: 'Gnome' },

  { category: 'Objects',     civilian: 'Candle',      spy: 'Incense' },
  { category: 'Objects',     civilian: 'Telescope',   spy: 'Microscope' },
  { category: 'Objects',     civilian: 'Thermos',     spy: 'Flask' },
  { category: 'Objects',     civilian: 'Postcard',    spy: 'Letter' },
  { category: 'Objects',     civilian: 'Zipper',      spy: 'Button' },
  { category: 'Objects',     civilian: 'Bell',        spy: 'Whistle' },
  { category: 'Objects',     civilian: 'Tape',        spy: 'Glue' },

  { category: 'Clothing',    civilian: 'Poncho',      spy: 'Cape' },
  { category: 'Clothing',    civilian: 'Sandals',     spy: 'Flip-Flops' },
  { category: 'Clothing',    civilian: 'Beret',       spy: 'Fedora' },
  { category: 'Clothing',    civilian: 'Overalls',    spy: 'Jumpsuit' },
  { category: 'Clothing',    civilian: 'Vest',        spy: 'Cardigan' },

  { category: 'Furniture',   civilian: 'Recliner',    spy: 'Bean Bag' },
  { category: 'Furniture',   civilian: 'Nightstand',  spy: 'End Table' },
  { category: 'Furniture',   civilian: 'Cradle',      spy: 'Crib' },
  { category: 'Furniture',   civilian: 'Ottoman',     spy: 'Footrest' },
  { category: 'Furniture',   civilian: 'Futon',       spy: 'Daybed' },
  { category: 'Furniture',   civilian: 'Armoire',     spy: 'Hutch' },

  { category: 'Toys / Games', civilian: 'Monopoly',   spy: 'Risk' },
  { category: 'Toys / Games', civilian: 'Jenga',      spy: 'Connect Four' },
  { category: 'Toys / Games', civilian: 'Trampoline', spy: 'Swing' },
  { category: 'Toys / Games', civilian: 'Dollhouse',  spy: 'Action Figure' },
  { category: 'Toys / Games', civilian: 'Tetris',     spy: 'Pac-Man' },
  { category: 'Toys / Games', civilian: 'Tag',        spy: 'Hide and Seek' },

  { category: 'Insects',     civilian: 'Moth',        spy: 'Butterfly' },
  { category: 'Insects',     civilian: 'Centipede',   spy: 'Millipede' },
  { category: 'Insects',     civilian: 'Caterpillar', spy: 'Inchworm' },
  { category: 'Insects',     civilian: 'Praying Mantis', spy: 'Stick Insect' },
  { category: 'Insects',     civilian: 'Cicada',      spy: 'Locust' },

  { category: 'Desserts',    civilian: 'Fudge',       spy: 'Toffee' },
  { category: 'Desserts',    civilian: 'Banana Split', spy: 'Sundae' },
  { category: 'Desserts',    civilian: 'Cinnamon Roll', spy: 'Danish' },
  { category: 'Desserts',    civilian: 'Baklava',     spy: 'Strudel' },
  { category: 'Desserts',    civilian: 'Pavlova',     spy: 'Trifle' },

  { category: 'Space',       civilian: 'Black Hole',  spy: 'Wormhole' },
  { category: 'Space',       civilian: 'Comet',       spy: 'Shooting Star' },
  { category: 'Space',       civilian: 'Space Station', spy: 'Satellite' },
  { category: 'Space',       civilian: 'Constellation', spy: 'Zodiac' },

  { category: 'Tools',       civilian: 'Tape Measure', spy: 'Ruler' },
  { category: 'Tools',       civilian: 'Clamp',       spy: 'Vise' },
  { category: 'Tools',       civilian: 'Chisel',      spy: 'File' },
  { category: 'Tools',       civilian: 'Blowtorch',   spy: 'Soldering Iron' },

  { category: 'Body',        civilian: 'Shoulder',    spy: 'Hip' },
  { category: 'Body',        civilian: 'Wrist',       spy: 'Ankle' },
  { category: 'Body',        civilian: 'Forehead',    spy: 'Chin' },
  { category: 'Body',        civilian: 'Rib',         spy: 'Spine' },

  // ---- new categories ----

  { category: 'Movies',      civilian: 'Horror',      spy: 'Thriller' },
  { category: 'Movies',      civilian: 'Comedy',      spy: 'Sitcom' },
  { category: 'Movies',      civilian: 'Documentary', spy: 'Biopic' },
  { category: 'Movies',      civilian: 'Musical',     spy: 'Concert' },
  { category: 'Movies',      civilian: 'Sequel',      spy: 'Reboot' },
  { category: 'Movies',      civilian: 'Animation',   spy: 'Stop Motion' },
  { category: 'Movies',      civilian: 'Director',    spy: 'Producer' },
  { category: 'Movies',      civilian: 'Popcorn',     spy: 'Candy Bar' },

  { category: 'Holidays',    civilian: 'Christmas',   spy: 'Hanukkah' },
  { category: 'Holidays',    civilian: 'Halloween',   spy: 'Day of the Dead' },
  { category: 'Holidays',    civilian: 'Easter',      spy: 'Passover' },
  { category: 'Holidays',    civilian: 'Valentine',   spy: 'Anniversary' },
  { category: 'Holidays',    civilian: 'Thanksgiving', spy: 'Harvest Festival' },
  { category: 'Holidays',    civilian: 'New Year',    spy: 'Carnival' },
  { category: 'Holidays',    civilian: 'Summer',      spy: 'Spring' },
  { category: 'Holidays',    civilian: 'Winter',      spy: 'Autumn' },

  { category: 'School',      civilian: 'Chalk',       spy: 'Marker' },
  { category: 'School',      civilian: 'Textbook',    spy: 'Notebook' },
  { category: 'School',      civilian: 'Backpack',    spy: 'Lunchbox' },
  { category: 'School',      civilian: 'Recess',      spy: 'Lunch Break' },
  { category: 'School',      civilian: 'Exam',        spy: 'Quiz' },
  { category: 'School',      civilian: 'Homework',    spy: 'Project' },
  { category: 'School',      civilian: 'Principal',   spy: 'Counselor' },
  { category: 'School',      civilian: 'Report Card', spy: 'Diploma' },

  { category: 'Kitchen',     civilian: 'Blender',     spy: 'Food Processor' },
  { category: 'Kitchen',     civilian: 'Toaster',     spy: 'Microwave' },
  { category: 'Kitchen',     civilian: 'Spatula',     spy: 'Tongs' },
  { category: 'Kitchen',     civilian: 'Whisk',       spy: 'Ladle' },
  { category: 'Kitchen',     civilian: 'Oven',        spy: 'Stovetop' },
  { category: 'Kitchen',     civilian: 'Colander',    spy: 'Strainer' },
  { category: 'Kitchen',     civilian: 'Cutting Board', spy: 'Rolling Pin' },
  { category: 'Kitchen',     civilian: 'Apron',       spy: 'Oven Mitt' },

  { category: 'Arts',        civilian: 'Painting',    spy: 'Sketch' },
  { category: 'Arts',        civilian: 'Pottery',     spy: 'Sculpture' },
  { category: 'Arts',        civilian: 'Ballet',      spy: 'Jazz Dance' },
  { category: 'Arts',        civilian: 'Origami',     spy: 'Papier-mache' },
  { category: 'Arts',        civilian: 'Graffiti',    spy: 'Mural' },
  { category: 'Arts',        civilian: 'Charcoal',    spy: 'Pastel' },
  { category: 'Arts',        civilian: 'Watercolor',  spy: 'Oil Paint' },
  { category: 'Arts',        civilian: 'Calligraphy', spy: 'Typography' },
];
